/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef LSUTILITIES_AUTODEFS_H
#define LSUTILITIES_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_LSUTILITIES_NAME "lsUtilities"
#define S3E_EXT_LSUTILITIES_HASH 0xe03710a0

#endif /* !LSUTILITIES_AUTODEFS_H */
